name: Android Nightly Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  nightly-debug:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Decode Keystore
        run: |
          echo "${{ secrets.SIGNING_KEY_STORE_BASE64 }}" | base64 -d > release.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release and Debug APKs
        run: ./gradlew assembleRelease assembleDebug -x lint
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/release.jks
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}

      - name: Delete existing nightly tag
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          delete_release: true
          tag_name: nightly
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Nightly Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: Nightly Build (Debug & Release)
          body: |
            最新のコミットによるデバッグおよびリリースビルドです。
            Commit: ${{ github.sha }}
          files: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/release/app-release.apk
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}